baseURL = "https://maliktafheem.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Malik Tafheem"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
publishdir="docs"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
    displayMode = "dark"
    title = "Malik Tafheem"
    author = "Malik Tafheem Ul Islam"
    description = "Hey there!!!!"
    profilePicture = "images/profile1.jpg"
    singleDateFormat = "Mon, Jan 2, 2006"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"